### ISSUE TITLE
Suggested updates

### ISSUE THREAD

**Issue by mpaget** [csiro-easi/easi-training-pc#1]
Some code update suggestions. Capturing here before prioritisation.

1. File: `easi-pc-py36/start-notebook.sh`
Suggestion: Contains "install ODC", which could be move out to another script.

2. File: `easi-pc-py36/start-singleuser.sh`
```
if [ ! -z "$JUPYTER_ENABLE_LAB" ]; then
  NOTEBOOK_BIN="jupyter labhub"
else
  NOTEBOOK_BIN=jupyterhub-singleuser
fi
```
Suggestion: Move out to a "start-jupyterhub.sh", perhaps which calls a common "start-common.sh""

3. datacube commands not default path when `docker exec -i -t [container] bash`
Suggestion: Add ~/.local/bin to user's path in ~/.bashrc or ~/.profile

**Comment by woodcockr** [comment]
The start scripting and paths have all been cleaned up.
I'm not moving out install ODC section just yet as it will be fixed by a refactor when aligning to ODC Docker environment as a base now we've sorted out a few things and Docker has a few more tricks up its sleeve.
