### ISSUE TITLE
green should have band_3 alias in LS8 pipeline

### ISSUE THREAD

**Issue by bosth** [csiro-easi/easi-training-pc#8]
https://github.com/csiro-easi/easi-training-pc/blob/3db668280b6cac6523616385507e77b2f6bbc7f0/work/data-pipelines/landsat-usgs/ls8_usgs_sr_albers_netcdf_ingest.yaml#L63-L71

Both green and red are aliased as `band_4`.

**Comment by woodcockr** [comment]
Fixed in 1.0.1 release #13
