### ISSUE TITLE
 building 'osgeo._gdal' extension 

### ISSUE THREAD

**Issue by fre171csiro** [csiro-easi/easi-training-pc#9]
I am current having an issue when doing 'docker-compose up' with the latest version

opendatacube_1  |     building 'osgeo._gdal' extension
opendatacube_1  |     creating build/temp.linux-x86_64-3.6
opendatacube_1  |     creating build/temp.linux-x86_64-3.6/extensions
opendatacube_1  |     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -I/usr/include/python3.6m -I/home/jovyan/.local/lib/python3.6/site-packages/numpy/core/include -I/usr/include -c extensions/gdal_wrap.cpp -o build/temp.linux-x86_64-3.6/extensions/gdal_wrap.o -I/usr/include/gdal
opendatacube_1  |     extensions/gdal_wrap.cpp: In function ?OSRSpatialReferenceShadow* GDALDatasetShadow_GetSpatialRef(GDALDatasetShadow*)?:
opendatacube_1  |     extensions/gdal_wrap.cpp:4672:32: error: ?GDALGetSpatialRef? was not declared in this scope
opendatacube_1  |          OGRSpatialReferenceH ref = GDALGetSpatialRef(self);
opendatacube_1  |                                     ^~~~~~~~~~~~~~~~~
opendatacube_1  |     extensions/gdal_wrap.cpp:4672:32: note: suggested alternative: ?OGR_L_GetSpatialRef?
opendatacube_1  |          OGRSpatialReferenceH ref = GDALGetSpatialRef(self);
opendatacube_1  |                                     ^~~~~~~~~~~~~~~~~
opendatacube_1  |                                     OGR_L_GetSpatialRef
opendatacube_1  |     extensions/gdal_wrap.cpp: In function ?void GDALDatasetShadow_SetSpatialRef(GDALDatasetShadow*, OSRSpatialReferenceShadow*)?:
opendatacube_1  |     extensions/gdal_wrap.cpp:4681:6: error: ?GDALSetSpatialRef? was not declared in this scope
opendatacube_1  |           GDALSetSpatialRef( self, (OGRSpatialReferenceH)srs );
opendatacube_1  |           ^~~~~~~~~~~~~~~~~
opendatacube_1  |     extensions/gdal_wrap.cpp:4681:6: note: suggested alternative: ?OGR_L_GetSpatialRef?
opendatacube_1  |           GDALSetSpatialRef( self, (OGRSpatialReferenceH)srs );
opendatacube_1  |           ^~~~~~~~~~~~~~~~~
opendatacube_1  |           OGR_L_GetSpatialRef
opendatacube_1  |     extensions/gdal_wrap.cpp: In function ?OSRSpatialReferenceShadow* GDALDatasetShadow_GetGCPSpatialRef(GDALDatasetShadow*)?:
opendatacube_1  |     extensions/gdal_wrap.cpp:4722:32: error: ?GDALGetGCPSpatialRef? was not declared in this scope
opendatacube_1  |          OGRSpatialReferenceH ref = GDALGetGCPSpatialRef(self);
opendatacube_1  |                                     ^~~~~~~~~~~~~~~~~~~~
opendatacube_1  |     extensions/gdal_wrap.cpp:4722:32: note: suggested alternative: ?OGR_L_GetSpatialRef?
opendatacube_1  |          OGRSpatialReferenceH ref = GDALGetGCPSpatialRef(self);
opendatacube_1  |                                     ^~~~~~~~~~~~~~~~~~~~
opendatacube_1  |                                     OGR_L_GetSpatialRef
opendatacube_1  |     extensions/gdal_wrap.cpp: In function ?CPLErr GDALDatasetShadow_SetGCPs2(GDALDatasetShadow*, int, const GDAL_GCP*, OSRSpatialReferenceShadow*)?:
opendatacube_1  |     extensions/gdal_wrap.cpp:4735:12: error: ?GDALSetGCPs2? was not declared in this scope
opendatacube_1  |          return GDALSetGCPs2( self, nGCPs, pGCPs, (OGRSpatialReferenceH)hSRS );
opendatacube_1  |                 ^~~~~~~~~~~~
opendatacube_1  |     extensions/gdal_wrap.cpp:4735:12: note: suggested alternative: ?GDALSetGCPs?
opendatacube_1  |          return GDALSetGCPs2( self, nGCPs, pGCPs, (OGRSpatialReferenceH)hSRS );
opendatacube_1  |                 ^~~~~~~~~~~~
opendatacube_1  |                 GDALSetGCPs
opendatacube_1  |     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
opendatacube_1  |
opendatacube_1  |     ----------------------------------------
opendatacube_1  | Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-rgka_oqu/gdal/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-39ltm5pf-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-rgka_oqu/gdal/

**Comment by fre171csiro** [comment]
Current work around I have changed the required version of gdal to 2.0.0 in the setup.py file in ~/odc

**Comment by fre171csiro** [comment]
Looks like this has been resolved in the latest version @woodcockr

**Comment by woodcockr** [comment]
Great that was the intent.
